CREATE TABLE estadio
(
    idEstadio NUMERIC(100) PRIMARY KEY,
    nome VARCHAR(50) CONSTRAINT NOT NULL,
    local1 VARCHAR(50) CONSTRAINT NOT NULL,
    UNIQUE (NOME)
    --UNIQUE (LOCAL1)
);

CREATE TABLE jogo
(
    idJogo NUMERIC PRIMARY KEY,
    data1 DATE CONSTRAINT jogo_data1_nn NOT NULL,
    hora_inicio TIME CONSTRAINT jogo_hora_inicio_nn NOT NULL,
    hora_fim TIME CONSTRAINT jogo_hora_fim_nn NOT NULL,
    estadio VARCHAR(50),
    FOREIGN KEY (estadio) REFERENCES idEstadio(estadio),
    CHECK (hora_fim > hora_inicio)
    --UNIQUE (data1, hora_inicio, hora_fim)
);

CREATE TABLE jogo_elem
(
    idJogo_fase_elem NUMERIC PRIMARY KEY,
    fase VARCHAR(50) CONSTRAINT jogo_elem_fase_nn NOT NULL,
    FOREIGN KEY (id_Jogo_fase_elem) REFERENCES idJogo(jogo),
);

CREATE TABLE jogo_grupo
(
    idJogo_fase_grupo NUMERIC,
    jornada VARCHAR(50) CONSTRAINT jogo_grupo_jornada_nn NOT NULL,
    FOREIGN KEY (idJogo_fase_grupo) REFERENCES idJogo(jogo),
    PRIMARY KEY (idJogo_fase_grupo)
);

CREATE TABLE grupos
(
    idGrupo NUMERIC PRIMARY KEY,
    idJogo_fase_grupo NUMERIC,
    pontos NUMERIC CONSTRAINT grupos_pontos_nn NOT NULL,
    lugar NUMERIC(4) CONSTRAINT grupos_lugar_nn NOT NULL,
    nome VARCHAR(50) CONSTRAINT grupos_nome_nn NOT NULL,
    FOREIGN KEY (idJogo_fase_grupo) REFERENCES idJogo_fase_grupo(jogo_grupo),
    UNIQUE (nome)
);

CREATE TABLE EQUIPA
(
    ID_EQUIPA NUMERIC,
    ID_GRUPO NUMERIC,
    PAIS VARCHAR(50),
    SIGLA VARCHAR(3),
    CONTINENTE VARCHAR(50),
    FOREIGN KEY (ID_GRUPO) REFERENCES ID_GRUPO(GRUPOS),
    PRIMARY KEY (ID_EQUIPA),
    UNIQUE (PAIS),
    UNIQUE (SIGLA)
);

CREATE TABLE JOGADOR
(
    ID_JOGADOR NUMERIC,
    ID_EQUIPA NUMERIC,
    ALTURA NUMERIC,
    PESO NUMERIC,
    NUMERO NUMERIC(99,1) CHECK (NUMERO >= 1 && NUMERO <= 99),
    NOME VARCHAR(50),
    DATA_NASCIMENTO DATE,
    FOREIGN KEY (ID_EQUIPA) REFERENCES ID_EQUIPA(EQUIPA),
    PRIMARY KEY (ID_JOGADOR),
    UNIQUE (NOME)
);

CREATE TABLE EVENTO
(
    ID_EVENTO NUMERIC,
    MINUTO NUMERIC(60),
    PRIMARY KEY (ID_EVENTO)
);

CREATE TABLE GOLO
(
    ID_GOLO NUMERIC,
    ID_SOFRE NUMERIC,
    ID_MARCA NUMERIC,
    ID_JOGADOR NUMERIC,
    FOREIGN KEY (ID_GOLO) REFERENCES ID_EVENTO(EVENTO),
    FOREIGN KEY (ID_SOFRE) REFERENCES ID_EQUIPA(EQUIPA),
    FOREIGN KEY (ID_MARCA) REFERENCES ID_EQUIPA(EQUIPA),
    FOREIGN KEY (ID_JOGADOR) REFERENCES ID_JOGADOR(JOGADOR),
    PRIMARY KEY (ID_GOLO)
);