CREATE TABLE ESTADIO
(
    ID_ESTADIO NUMERIC,
    NOME VARCHAR(50),
    LOCAL1 VARCHAR(50),
    PRIMARY KEY (ID_ESTADIO)
);

CREATE TABLE JOGO
(
    IDJOGO NUMERIC,
    DATA1 DATE,
    HORA_INICIO TIME,
    HORA_FIM TIME,
    ESTADIO VARCHAR(50),
    FOREIGN KEY (ESTADIO) REFERENCES IDESTADIO(ESTADIO)
);

CREATE TABLE JOGO_ELEM
(
    ID_JOGO_FASE_ELEM NUMERIC,
    FASE VARCHAR(50),
    FOREIGN KEY (ID_JOGO_FASE_ELEM) REFERENCES IDJOGO(JOGO),
    PRIMARY KEY (ID_JOGO_FASE_ELEM)
);

CREATE TABLE JOGO_GRUPO
(
    ID_JOGO_FASE_GRUPO NUMERIC,
    JORNADA VARCHAR(50),
    FOREIGN KEY (ID_JOGO_FASE_GRUPO) REFERENCES IDJOGO(JOGO),
    PRIMARY KEY (ID_JOGO_FASE_GRUPO)
);

CREATE TABLE GRUPOS
(
    ID_GRUPO NUMERIC,
    ID_JOGO_FASE_GRUPO NUMERIC,
    PONTOS NUMERIC,
    LUGAR NUMERIC,
    NOME VARCHAR(50),
    FOREIGN KEY (ID_JOGO_FASE_GRUPO) REFERENCES ID_JOGO_FASE_GRUPO(JOGO_GRUPO),
    PRIMARY KEY (ID_GRUPO)
);

CREATE TABLE EQUIPA
(
    ID_EQUIPA NUMERIC,
    ID_GRUPO NUMERIC,
    PAIS VARCHAR(50),
    SIGLA VARCHAR(3),
    CONTINENTE VARCHAR(50),
    FOREIGN KEY (ID_GRUPO) REFERENCES ID_GRUPO(GRUPOS),
    PRIMARY KEY (ID_EQUIPA)
);

CREATE TABLE JOGADOR
(
    ID_JOGADOR NUMERIC,
    ID_EQUIPA NUMERIC,
    ALTURA NUMERIC,
    PESO NUMERIC,
    NUMERO NUMERIC(99,1),
    NOME VARCHAR(50),
    DATA_NASCIMENTO DATE,
    FOREIGN KEY (ID_EQUIPA) REFERENCES ID_EQUIPA(EQUIPA),
    PRIMARY KEY (ID_JOGADOR)
);

CREATE TABLE EVENTO
(
    ID_EVENTO NUMERIC,
    MINUTO NUMERIC(60),
    PRIMARY KEY (ID_EVENTO)
);

CREATE TABLE GOLO
(
    ID_GOLO NUMERIC,
    ID_SOFRE NUMERIC,
    ID_MARCA NUMERIC,
    ID_JOGADOR NUMERIC,
    FOREIGN KEY (ID_GOLO) REFERENCES ID_EVENTO(EVENTO),
    FOREIGN KEY (ID_SOFRE) REFERENCES ID_EQUIPA(EQUIPA),
    FOREIGN KEY (ID_MARCA) REFERENCES ID_EQUIPA(EQUIPA),
    FOREIGN KEY (ID_JOGADOR) REFERENCES ID_JOGADOR(JOGADOR),
    PRIMARY KEY (ID_GOLO)
);