CREATE TABLE ESTADIO
(
    IDESTADIO NUMERIC(),
    NOME VARCHAR(50),
    LOCAL VARCHAR(50),
    PRIMARY KEY (IDESTADIO)
);

CREATE TABLE JOGO
(
    IDJOGO NUMERIC(),
    DATA DATE(),
    HORA_INICIO TIME(),
    HORA_FIM TIME(),
    FOREIGN KEY (ESTADIO) REFERENCES IDESTADIO(ESTADIO)
);

CREATE TABLE JOGO_ELEM
(
    FOREIGN KEY (ID_JOGO_FASE_ELEM) REFERENCES 
);